export const PLUS_BUTTON_CLICKED = 'PLUS_BUTTON_CLICKED';
export const MINUS_BUTTON_CLICKED = 'MINUS_BUTTON_CLICKED';
export const MULTI_BUTTON_CLICKED = 'MULTI_BUTTON_CLICKED';
export const DIVIDE_BUTTON_CLICKED = 'DIVIDE_BUTTON_CLICKED';
export const EQUAL_BUTTON_CLICKED = 'EQUAL_BUTTON_CLICKED';
export const CLEAR_OPE_BUTTON_CLICKED = 'CLEAR_OPE_BUTTON_CLICKED';

export const ADD_NUMBER = 'ADD_NUMBER';
export const MINUS_NUMBER = 'MINUS_NUMBER';
export const MULTI_NUMBER = 'MULTI_NUMBER';
export const DIVIDE_NUMBER = 'DIVIDE_NUMBER';
export const EQUAL_NUMBER = 'EQUAL_NUMBER';
export const CLEAR_NUMBER = 'CLEAR_NUMBER';


export const NUM_BUTTON_CLICKED = 'NUM_BUTTON_CLICKED';
export const DOT_BUTTON_CLICKED = 'DOT_BUTTON_CLICKED';
export const CLEAR_NUM_BUTTON_CLICKED = 'CLEAR_NUM_BUTTON_CLICKED';

